export default [
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/1/18"),
        "Country": "SK",
        "Amount": 76.9,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "U ZLATEHO VODNIKA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/3/18"),
        "Country": "SK",
        "Amount": 100.0,
        "Device": "ATM",
        "Location": "Slovakia",
        "Mechant Type": "Financial Institutions - Automated Cash Disbursements",
        "Merchant Name": "TB",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/6/18"),
        "Country": "SK",
        "Amount": 113.62,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "U ZLATEHO VODNIKA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/8/18"),
        "Country": "NL",
        "Amount": 111.07,
        "Device": "Internet",
        "Location": "Outside Slovakia",
        "Mechant Type": "Taxicabs/Limousines",
        "Merchant Name": "UBER BV",
        "Description": "AMSTERDAM"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/11/18"),
        "Country": "AT",
        "Amount": 132.0,
        "Device": "Terminal",
        "Location": "Outside Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "GEORGES CAFE",
        "Description": "WIEN"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/15/18"),
        "Country": "SK",
        "Amount": 146.99,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "U ZLATEHO VODNIKA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/16/18"),
        "Country": "SK",
        "Amount": 14.69,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Drug Stores & Pharmacies",
        "Merchant Name": "BENU SK",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/18/18"),
        "Country": "SK",
        "Amount": 4.55,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "U ZLATEHO VODNIKA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/19/18"),
        "Country": "SK",
        "Amount": 1500.0,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Jewelry Stores",
        "Merchant Name": "ALO DIAMONDS,BA,PRIBINOVA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/19/18"),
        "Country": "NL",
        "Amount": 63.25,
        "Device": "Internet",
        "Location": "Outside Slovakia",
        "Mechant Type": "Taxicabs/Limousines",
        "Merchant Name": "UBER BV",
        "Description": "AMSTERDAM"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/19/18"),
        "Country": "SK",
        "Amount": 48.25,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Misc Food Stores - Default",
        "Merchant Name": "STARY OTEC",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/21/18"),
        "Country": "AT",
        "Amount": 26.06,
        "Device": "Terminal",
        "Location": "Outside Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "GEORGES CAFE",
        "Description": "WIEN"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/21/18"),
        "Country": "NL",
        "Amount": 14.25,
        "Device": "Internet",
        "Location": "Outside Slovakia",
        "Mechant Type": "Taxicabs/Limousines",
        "Merchant Name": "UBER BV",
        "Description": "AMSTERDAM"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/23/18"),
        "Country": "SK",
        "Amount": 93.25,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Dentists/Orthodontists",
        "Merchant Name": "MARTIN DENTAL CENTER S.R.",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/25/18"),
        "Country": "SK",
        "Amount": 144.79,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "U ZLATEHO VODNIKA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/28/18"),
        "Country": "SK",
        "Amount": 118.37,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "U ZLATEHO VODNIKA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/29/18"),
        "Country": "SK",
        "Amount": 500.0,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Clothing",
        "Merchant Name": "SVADOBNY SALON",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/1/18"),
        "Country": "AT",
        "Amount": 114.76,
        "Device": "Terminal",
        "Location": "Outside Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "GEORGES CAFE",
        "Description": "WIEN"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/3/18"),
        "Country": "SK",
        "Amount": 91.73,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Drug Stores & Pharmacies",
        "Merchant Name": "BENU SK",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/4/18"),
        "Country": "SK",
        "Amount": 138.87,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "U ZLATEHO VODNIKA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/5/18"),
        "Country": "SK",
        "Amount": 137.26,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "U ZLATEHO VODNIKA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/5/18"),
        "Country": "NL",
        "Amount": 103.66,
        "Device": "Internet",
        "Location": "Outside Slovakia",
        "Mechant Type": "Taxicabs/Limousines",
        "Merchant Name": "UBER BV",
        "Description": "AMSTERDAM"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/8/18"),
        "Country": "AT",
        "Amount": 71.74,
        "Device": "Terminal",
        "Location": "Outside Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "GEORGES CAFE",
        "Description": "WIEN"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/10/18"),
        "Country": "AT",
        "Amount": 66.1,
        "Device": "Terminal",
        "Location": "Outside Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "GEORGES CAFE",
        "Description": "WIEN"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/12/18"),
        "Country": "AT",
        "Amount": 77.75,
        "Device": "Terminal",
        "Location": "Outside Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "GEORGES CAFE",
        "Description": "WIEN"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/14/18"),
        "Country": "AT",
        "Amount": 95.71,
        "Device": "Terminal",
        "Location": "Outside Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "GEORGES CAFE",
        "Description": "WIEN"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/15/18"),
        "Country": "AT",
        "Amount": 130.48,
        "Device": "Terminal",
        "Location": "Outside Slovakia",
        "Mechant Type": "Restaurants",
        "Merchant Name": "GEORGES CAFE",
        "Description": "WIEN"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/17/18"),
        "Country": "NL",
        "Amount": 143.42,
        "Device": "Internet",
        "Location": "Outside Slovakia",
        "Mechant Type": "Taxicabs/Limousines",
        "Merchant Name": "UBER BV",
        "Description": "AMSTERDAM"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/19/18"),
        "Country": "SK",
        "Amount": 4.66,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Misc Food Stores - Default",
        "Merchant Name": "STARY OTEC",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/24/18"),
        "Country": "SK",
        "Amount": 1.52,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Misc Food Stores - Default",
        "Merchant Name": "STARY OTEC",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("2/24/18"),
        "Country": "NL",
        "Amount": 67.42,
        "Device": "Internet",
        "Location": "Outside Slovakia",
        "Mechant Type": "Taxicabs/Limousines",
        "Merchant Name": "UBER BV",
        "Description": "AMSTERDAM"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("3/2/18"),
        "Country": "SK",
        "Amount": 127.72,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Grocery Stores/Supermarkets",
        "Merchant Name": "BILLA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("3/3/18"),
        "Country": "SK",
        "Amount": 45.52,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Grocery Stores/Supermarkets",
        "Merchant Name": "BILLA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("3/9/18"),
        "Country": "SK",
        "Amount": 54.55,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Grocery Stores/Supermarkets",
        "Merchant Name": "BILLA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("3/28/18"),
        "Country": "SK",
        "Amount": 8.45,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Grocery Stores/Supermarkets",
        "Merchant Name": "BILLA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("1/7/18"),
        "Country": "SK",
        "Amount": 120.0,
        "Device": "TB App",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": "SVADBA ZALOHA"
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("1/12/18"),
        "Country": "SK",
        "Amount": 20.0,
        "Device": " ",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "ZSE ENERGIA, A.S.",
        "Description": ""
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("1/15/18"),
        "Country": "SK",
        "Amount": 1500.0,
        "Device": " ",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": "NAJOMNE"
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("1/21/18"),
        "Country": "SK",
        "Amount": 39.47,
        "Device": " ",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": ""
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("1/28/18"),
        "Country": "SK",
        "Amount": 50.0,
        "Device": "VIAMO",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": "KYTICA"
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("2/3/18"),
        "Country": "SK",
        "Amount": 117.26,
        "Device": " ",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "RTVS",
        "Description": ""
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("2/14/18"),
        "Country": "SK",
        "Amount": 1500.0,
        "Device": " ",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": "NAJOMNE"
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("2/21/18"),
        "Country": "SK",
        "Amount": 20.0,
        "Device": " ",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "ZSE ENERGIA, A.S.",
        "Description": ""
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("2/27/18"),
        "Country": "SK",
        "Amount": 74.63,
        "Device": "TB App",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": "NEMECKY KURZ A1.3"
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("3/6/18"),
        "Country": "SK",
        "Amount": 4.0,
        "Device": " ",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "ROZHLAS A TELEVIZIA SLOVENSKA",
        "Description": ""
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Debit",
        "Date": new Date("3/12/18"),
        "Country": "SK",
        "Amount": 500.0,
        "Device": "VIAMO",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": "PNEUMATIKY"
    },
    {
        "Type": "Card",
        "Debit/Credit": "Debit",
        "Date": new Date("1/1/18"),
        "Country": "SK",
        "Amount": 58.0,
        "Device": "Terminal",
        "Location": "Slovakia",
        "Mechant Type": "Grocery Stores/Supermarkets",
        "Merchant Name": "BILLA",
        "Description": "BRATISLAVA"
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Credit",
        "Date": new Date("2/4/18"),
        "Country": "SK",
        "Amount": 91.15,
        "Device": "VIAMO",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": ""
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Credit",
        "Date": new Date("2/11/18"),
        "Country": "SK",
        "Amount": 3000.0,
        "Device": " ",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": "SVADBA CESTA"
    },
    {
        "Type": "Transfer",
        "Debit/Credit": "Credit",
        "Date": new Date("3/2/18"),
        "Country": "SK",
        "Amount": 100.0,
        "Device": " ",
        "Location": "Slovakia",
        "Mechant Type": "",
        "Merchant Name": "---",
        "Description": "SVADOBNE ALBUMY"
    }
]